config/routes.rb
SoulmateExample::Application.routes.draw do
  get "people/index"

  get "people/autocomplete_person_name"

  root :to => 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  after_save :load_into_soulmate

  def load_into_soulmate
    loader = Soulmate::Loader.new("person")
    loader.add("term" => name, "id" => id)
  end

  def self.search(term)
    matches = Soulmate::Matcher.new('person').matches_for_term(term)
    matches.collect {|match| {"id" => match["id"], "label" => match["term"], "value" => match["term"] } }
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  end

  def autocomplete_person_name
    render :json => Person.search(params['term'])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoulmateExample</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/autocomplete_person_name.html.erb
<h1>People#autocomplete_person_name</h1>
<p>Find me in app/views/people/autocomplete_person_name.html.erb</p>

app/views/people/index.html.erb
Please enter the name of a person:
<%= text_field_tag 'person_name' %>

<script>
$(function() {
  $("#person_name" ).autocomplete({
    source: "<%= people_autocomplete_person_name_path %>"
  });
})
</script>